/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: /app/abacos/app/abacos-dds/idl/packet.idl
  Source: packet.hpp
  Cyclone DDS: v0.11.0

*****************************************************************/
#ifndef DDSCXX_PACKET_HPP_FB1EB195E92A128184547A1CCDFC6580
#define DDSCXX_PACKET_HPP_FB1EB195E92A128184547A1CCDFC6580

#include <utility>
#include <ostream>
#include <cstdint>
#include <string>

namespace Packet
{
class PacketMessage
{
private:
 int32_t id_ = 0;
 std::string payload_;
 uint64_t abacos_publisher_time_stamp_ns_ = 0;
 uint64_t dds_publisher_time_stamp_ns_ = 0;
 uint64_t dds_subscriber_time_stamp_ns_ = 0;
 uint64_t abacos_subscriber_time_stamp_ns_ = 0;

public:
  PacketMessage() = default;

  explicit PacketMessage(
    int32_t id,
    const std::string& payload,
    uint64_t abacos_publisher_time_stamp_ns,
    uint64_t dds_publisher_time_stamp_ns,
    uint64_t dds_subscriber_time_stamp_ns,
    uint64_t abacos_subscriber_time_stamp_ns) :
    id_(id),
    payload_(payload),
    abacos_publisher_time_stamp_ns_(abacos_publisher_time_stamp_ns),
    dds_publisher_time_stamp_ns_(dds_publisher_time_stamp_ns),
    dds_subscriber_time_stamp_ns_(dds_subscriber_time_stamp_ns),
    abacos_subscriber_time_stamp_ns_(abacos_subscriber_time_stamp_ns) { }

  int32_t id() const { return this->id_; }
  int32_t& id() { return this->id_; }
  void id(int32_t _val_) { this->id_ = _val_; }
  const std::string& payload() const { return this->payload_; }
  std::string& payload() { return this->payload_; }
  void payload(const std::string& _val_) { this->payload_ = _val_; }
  void payload(std::string&& _val_) { this->payload_ = std::move(_val_); }
  uint64_t abacos_publisher_time_stamp_ns() const { return this->abacos_publisher_time_stamp_ns_; }
  uint64_t& abacos_publisher_time_stamp_ns() { return this->abacos_publisher_time_stamp_ns_; }
  void abacos_publisher_time_stamp_ns(uint64_t _val_) { this->abacos_publisher_time_stamp_ns_ = _val_; }
  uint64_t dds_publisher_time_stamp_ns() const { return this->dds_publisher_time_stamp_ns_; }
  uint64_t& dds_publisher_time_stamp_ns() { return this->dds_publisher_time_stamp_ns_; }
  void dds_publisher_time_stamp_ns(uint64_t _val_) { this->dds_publisher_time_stamp_ns_ = _val_; }
  uint64_t dds_subscriber_time_stamp_ns() const { return this->dds_subscriber_time_stamp_ns_; }
  uint64_t& dds_subscriber_time_stamp_ns() { return this->dds_subscriber_time_stamp_ns_; }
  void dds_subscriber_time_stamp_ns(uint64_t _val_) { this->dds_subscriber_time_stamp_ns_ = _val_; }
  uint64_t abacos_subscriber_time_stamp_ns() const { return this->abacos_subscriber_time_stamp_ns_; }
  uint64_t& abacos_subscriber_time_stamp_ns() { return this->abacos_subscriber_time_stamp_ns_; }
  void abacos_subscriber_time_stamp_ns(uint64_t _val_) { this->abacos_subscriber_time_stamp_ns_ = _val_; }

  bool operator==(const PacketMessage& _other) const
  {
    (void) _other;
    return id_ == _other.id_ &&
      payload_ == _other.payload_ &&
      abacos_publisher_time_stamp_ns_ == _other.abacos_publisher_time_stamp_ns_ &&
      dds_publisher_time_stamp_ns_ == _other.dds_publisher_time_stamp_ns_ &&
      dds_subscriber_time_stamp_ns_ == _other.dds_subscriber_time_stamp_ns_ &&
      abacos_subscriber_time_stamp_ns_ == _other.abacos_subscriber_time_stamp_ns_;
  }

  bool operator!=(const PacketMessage& _other) const
  {
    return !(*this == _other);
  }

};

std::ostream& operator<<(std::ostream& os, ::Packet::PacketMessage const& rhs);

} //namespace Packet

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::Packet::PacketMessage>::getTypeName()
{
  return "Packet::PacketMessage";
}

template <> constexpr bool TopicTraits<::Packet::PacketMessage>::isSelfContained()
{
  return false;
}

template <> constexpr bool TopicTraits<::Packet::PacketMessage>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPELIB
template<> constexpr unsigned int TopicTraits<::Packet::PacketMessage>::type_map_blob_sz() { return 510; }
template<> constexpr unsigned int TopicTraits<::Packet::PacketMessage>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::Packet::PacketMessage>::type_map_blob() {
  alignas(4) static const uint8_t blob[] = {
 0x8b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0x66,  0x55,  0x04,  0xdd,  0x9c,  0x18,  0xcc, 
 0xe7,  0x7d,  0x0c,  0xc1,  0x53,  0x9b,  0xaf,  0x00,  0x73,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x63,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x04,  0xb8,  0x0b,  0xb7,  0x74,  0x00, 
 0x0c,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00,  0x32,  0x1c,  0x3c,  0xf4, 
 0x0b,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x08,  0x8f,  0x70,  0x6e,  0x30,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x08,  0xe7,  0x89,  0x53,  0xa7,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x08,  0x57,  0x10,  0x55,  0xff,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x08,  0xea,  0x37,  0x38,  0xca,  0x00, 
 0x42,  0x01,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0xf8,  0xd0,  0x68,  0x27,  0x68,  0x54,  0x56, 
 0x67,  0xe9,  0x5c,  0xe6,  0x88,  0xb5,  0xba,  0x00,  0x2a,  0x01,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x1e,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x16,  0x00,  0x00,  0x00,  0x50,  0x61,  0x63,  0x6b, 
 0x65,  0x74,  0x3a,  0x3a,  0x50,  0x61,  0x63,  0x6b,  0x65,  0x74,  0x4d,  0x65,  0x73,  0x73,  0x61,  0x67, 
 0x65,  0x00,  0x00,  0x00,  0xfe,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00,  0x11,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x04,  0x00,  0x03,  0x00,  0x00,  0x00,  0x69,  0x64,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x16,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00, 
 0x08,  0x00,  0x00,  0x00,  0x70,  0x61,  0x79,  0x6c,  0x6f,  0x61,  0x64,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x2d,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x08,  0x00,  0x1f,  0x00,  0x00,  0x00, 
 0x61,  0x62,  0x61,  0x63,  0x6f,  0x73,  0x5f,  0x70,  0x75,  0x62,  0x6c,  0x69,  0x73,  0x68,  0x65,  0x72, 
 0x5f,  0x74,  0x69,  0x6d,  0x65,  0x5f,  0x73,  0x74,  0x61,  0x6d,  0x70,  0x5f,  0x6e,  0x73,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x2a,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x08,  0x00, 
 0x1c,  0x00,  0x00,  0x00,  0x64,  0x64,  0x73,  0x5f,  0x70,  0x75,  0x62,  0x6c,  0x69,  0x73,  0x68,  0x65, 
 0x72,  0x5f,  0x74,  0x69,  0x6d,  0x65,  0x5f,  0x73,  0x74,  0x61,  0x6d,  0x70,  0x5f,  0x6e,  0x73,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x2b,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x08,  0x00, 
 0x1d,  0x00,  0x00,  0x00,  0x64,  0x64,  0x73,  0x5f,  0x73,  0x75,  0x62,  0x73,  0x63,  0x72,  0x69,  0x62, 
 0x65,  0x72,  0x5f,  0x74,  0x69,  0x6d,  0x65,  0x5f,  0x73,  0x74,  0x61,  0x6d,  0x70,  0x5f,  0x6e,  0x73, 
 0x00,  0x00,  0x00,  0x00,  0x2e,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x08,  0x00, 
 0x20,  0x00,  0x00,  0x00,  0x61,  0x62,  0x61,  0x63,  0x6f,  0x73,  0x5f,  0x73,  0x75,  0x62,  0x73,  0x63, 
 0x72,  0x69,  0x62,  0x65,  0x72,  0x5f,  0x74,  0x69,  0x6d,  0x65,  0x5f,  0x73,  0x74,  0x61,  0x6d,  0x70, 
 0x5f,  0x6e,  0x73,  0x00,  0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0xf2,  0xf8,  0xd0,  0x68,  0x27,  0x68,  0x54,  0x56,  0x67,  0xe9,  0x5c,  0xe6,  0x88,  0xb5,  0xba,  0xf1, 
 0x66,  0x55,  0x04,  0xdd,  0x9c,  0x18,  0xcc,  0xe7,  0x7d,  0x0c,  0xc1,  0x53,  0x9b,  0xaf, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::Packet::PacketMessage>::type_info_blob() {
  alignas(4) static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0x66,  0x55,  0x04,  0xdd,  0x9c,  0x18,  0xcc,  0xe7,  0x7d,  0x0c,  0xc1, 
 0x53,  0x9b,  0xaf,  0x00,  0x77,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0xf8,  0xd0,  0x68,  0x27,  0x68,  0x54,  0x56,  0x67,  0xe9,  0x5c,  0xe6, 
 0x88,  0xb5,  0xba,  0x00,  0x2e,  0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPELIB

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::Packet::PacketMessage>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::Packet::PacketMessage>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::Packet::PacketMessage);

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
const propvec &get_type_props<::Packet::PacketMessage>();

namespace {
  static const volatile propvec &properties___Packet__PacketMessage = get_type_props<::Packet::PacketMessage>();
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::Packet::PacketMessage& instance, const entity_properties_t *props) {
  (void)instance;
  member_id_set member_ids;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.id()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write_string(streamer, instance.payload(), 0))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.abacos_publisher_time_stamp_ns()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.dds_publisher_time_stamp_ns()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.dds_subscriber_time_stamp_ns()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.abacos_subscriber_time_stamp_ns()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props, member_ids);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::Packet::PacketMessage& instance, key_mode key) {
  const auto &props = get_type_props<::Packet::PacketMessage>();
  str.set_mode(cdr_stream::stream_mode::write, key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::Packet::PacketMessage& instance, const entity_properties_t *props) {
  (void)instance;
  member_id_set member_ids;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.id()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read_string(streamer, instance.payload(), 0))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.abacos_publisher_time_stamp_ns()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.dds_publisher_time_stamp_ns()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.dds_subscriber_time_stamp_ns()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.abacos_subscriber_time_stamp_ns()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props, member_ids);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::Packet::PacketMessage& instance, key_mode key) {
  const auto &props = get_type_props<::Packet::PacketMessage>();
  str.set_mode(cdr_stream::stream_mode::read, key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::Packet::PacketMessage& instance, const entity_properties_t *props) {
  (void)instance;
  member_id_set member_ids;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.id()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move_string(streamer, instance.payload(), 0))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.abacos_publisher_time_stamp_ns()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.dds_publisher_time_stamp_ns()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.dds_subscriber_time_stamp_ns()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.abacos_subscriber_time_stamp_ns()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props, member_ids);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::Packet::PacketMessage& instance, key_mode key) {
  const auto &props = get_type_props<::Packet::PacketMessage>();
  str.set_mode(cdr_stream::stream_mode::move, key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::Packet::PacketMessage& instance, const entity_properties_t *props) {
  (void)instance;
  member_id_set member_ids;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.id()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max_string(streamer, instance.payload(), 0))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.abacos_publisher_time_stamp_ns()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.dds_publisher_time_stamp_ns()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.dds_subscriber_time_stamp_ns()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.abacos_subscriber_time_stamp_ns()))
        return false;
      if (!streamer.finish_member(*prop, member_ids))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props, member_ids);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::Packet::PacketMessage& instance, key_mode key) {
  const auto &props = get_type_props<::Packet::PacketMessage>();
  str.set_mode(cdr_stream::stream_mode::max, key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_PACKET_HPP_FB1EB195E92A128184547A1CCDFC6580
