/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: /app/abacos/app/abacos-dds/idl/packet.idl
  Source: packet.cpp
  Cyclone DDS: v0.11.0

*****************************************************************/
#include "packet.hpp"

#include <org/eclipse/cyclonedds/util/ostream_operators.hpp>

namespace Packet
{
std::ostream& operator<<(std::ostream& os, ::Packet::PacketMessage const& rhs)
{
  (void) rhs;
  os << "[";
  os << "id: " << rhs.id();
  os << ", payload: " << rhs.payload();
  os << ", abacos_publisher_time_stamp_ns: " << rhs.abacos_publisher_time_stamp_ns();
  os << ", dds_publisher_time_stamp_ns: " << rhs.dds_publisher_time_stamp_ns();
  os << ", dds_subscriber_time_stamp_ns: " << rhs.dds_subscriber_time_stamp_ns();
  os << ", abacos_subscriber_time_stamp_ns: " << rhs.abacos_subscriber_time_stamp_ns();
  os << "]";
  return os;
}

} //namespace Packet

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
const propvec &get_type_props<::Packet::PacketMessage>() {
  static std::mutex mtx;
  static propvec props;
  static std::atomic_bool initialized {false};
  key_endpoint keylist;
  if (initialized.load(std::memory_order_relaxed))
    return props;
  std::lock_guard<std::mutex> lock(mtx);
  if (initialized.load(std::memory_order_relaxed))
    return props;
  props.clear();

  props.push_back(entity_properties_t(0, 0, false, bit_bound::bb_unset, extensibility::ext_final));  //root
  props.push_back(entity_properties_t(1, 0, false, get_bit_bound<int32_t>(), extensibility::ext_final, false));  //::id
  props.push_back(entity_properties_t(1, 1, false, bit_bound::bb_unset, extensibility::ext_final, false));  //::payload
  props.push_back(entity_properties_t(1, 2, false, get_bit_bound<uint64_t>(), extensibility::ext_final, false));  //::abacos_publisher_time_stamp_ns
  props.push_back(entity_properties_t(1, 3, false, get_bit_bound<uint64_t>(), extensibility::ext_final, false));  //::dds_publisher_time_stamp_ns
  props.push_back(entity_properties_t(1, 4, false, get_bit_bound<uint64_t>(), extensibility::ext_final, false));  //::dds_subscriber_time_stamp_ns
  props.push_back(entity_properties_t(1, 5, false, get_bit_bound<uint64_t>(), extensibility::ext_final, false));  //::abacos_subscriber_time_stamp_ns

  entity_properties_t::finish(props, keylist);
  initialized.store(true, std::memory_order_release);
  return props;
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

